### ISSUE TITLE
Header component toevoegen

### ISSUE THREAD

**Issue by ghost** [WesleySchorel/Toolgankelijk-Sprint-16#6]
DOD
- [x]  Bread-crumbs navigatie
- [x]  Dynamische heading
- [x]  Complete header element responsive maken
- [x]  Header component toevoegen aan de library

**Comment by tom-2810** [comment]
DOD

- [ ] Bread-crumbs navigatie
- [ ] Dynamische heading
- [ ] Complete header element responsive maken
- [ ] Header component toevoegen aan de library
